language: csharp
mono: none
sudo: required


env:
- DOCKER_COMPOSE_VERSION=1.21.1


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker ps


stages:
- build_and_push
#- deploy


jobs:
    include:
        - stage: build_and_push
          script: 
            - docker login --username=fhspwr --password=qwerty123@
            - docker-compose build ./Fault-handling-system/
            #- docker build -t fault-handling-system /home/travis/build/TadeuszNorek/fault-handling-system-test/Fault-handling-system/
            #- docker tag fault-handling-system fhspwr/fault-handling-system-test
            #- docker push fhspwr/fault-handling-system-test   
        #- stage: deploy
        #  script:
            #- docker login --username=226098@student.pwr.edu.pl --password=1e3ad94a-c454-4a02-9643-ed40130e9924 registry.heroku.com
            #- docker pull registry.hub.docker.com/fhspwr/fault-handling-system-test:latest
            #- docker tag registry.hub.docker.com/fhspwr/fault-handling-system-test:latest registry.heroku.com/fault-handling-system/web
            #- docker push registry.heroku.com/fault-handling-system/web
